en:
  languageName: English
  weight: 1
  title: "Geographers for Justice in Palestine"
  params:
    description: "Geographers for Justice in Palestine"
    main_cta:
      text: "Get in touch"
      link: "who-we-are#get-in-touch"
    footer_cta:
      text: "Get in touch"
      link: "who-we-are#get-in-touch"
  menu:
    main:
    - identifier: "petition"
      name: "Sign the petition"
      url: "/petition/"
      weight: 1
    - identifier: "join"
      name: "Join our campaign"
      url: "/join/"
      weight: 2
    - identifier: "who-we-are"
      name: "Who we are"
      url: "/who-we-are"
      weight: 3
    - identifier: "endorsements"
      name: "Endorsements"
      url: "/endorsements"
      weight: 4